attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.2
embedding_labels:
  band:
    ? !!binary |
      WQ==
    : 0
    ? !!binary |
      Zw==
    : 1
    ? !!binary |
      aQ==
    : 2
    ? !!binary |
      cg==
    : 3
    ? !!binary |
      dQ==
    : 4
    ? !!binary |
      eg==
    : 5
embedding_paddings: []
embedding_sizes:
  band: !!python/tuple
  - 6
  - 4
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 128
learning_rate: 0.01
log_gradient_flow: false
log_interval: 30
log_val_interval: 30
lstm_layers: 2
max_encoder_length: 165
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 4
output_transformer: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
  add_nan: false
  classes_:
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      CgAAAAAAAAA=
    : 0
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VAAAAAAAAAA=
    : 1
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      WQAAAAAAAAA=
    : 2
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      WgAAAAAAAAA=
    : 3
  classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
    - *id001
    - false
    - !!binary |
      CgAAAAAAAABUAAAAAAAAAFkAAAAAAAAAWgAAAAAAAAA=
  warn: true
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 2
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- redshift
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder:
- band
time_varying_reals_decoder:
- fluxcalerr
- mjd
- relative_time_idx
time_varying_reals_encoder:
- fluxcalerr
- mjd
- relative_time_idx
- fluxcal
weight_decay: 0.0
x_categoricals:
- band
x_reals:
- redshift
- encoder_length
- fluxcalerr
- mjd
- relative_time_idx
- fluxcal
